name: ingetin_task_reminder_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  expand_widget: ^3.1.1
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_dynamic_links: ^5.2.0
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_expandable_widget: ^1.0.5
  google_sign_in: ^6.1.0
  hexcolor: ^3.0.1
  intl: ^0.17.0
  lottie: ^2.3.2
  responsive_sizer: ^3.1.1
  sizer: ^2.0.15
  alarm: ^1.0.5
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  tutorial_coach_mark: ^1.2.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_ingetin.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_ingetin.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_ingetin.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_ingetin.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/logo_ingetin.png
    - assets/lottie/
    - assets/audio/